# Local test. Assuming docker image is built locally @ jerry

services:
  jerry-bot:
    image: jerry:latest # Local image built from Dockerfile
    container_name: jerry-bot
    volumes:
      - ./data:/app/data
    environment:
      - ENV=development
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: jerry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: jerry-postgres
    environment:
      - POSTGRES_USER=jerry
      - POSTGRES_PASSWORD=jerryjerryjerry
      - POSTGRES_DB=css
    ports:
      - "5432:5432"

volumes:
  redis-data:
  postgres-data: