name: jerry-bot
services:
  # jerry-bot:
  #   image: ghcr.io/squid1127/jerry-bot:main
  #   container_name: jerry-bot
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./store:/app/store
  #     - ./communal:/app/communal

  redis:
    image: redis:latest
    container_name: jerry-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: jerry-bot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: