# squid-core Project Manifest
[project]
name = "jerry_bot"
friendly_name = "Jerry Bot"

[bot]
cmd_prefix = "jerry-"
intents = ["guilds", "messages", "message_content", "members", "voice_states"]

[bot.cli]
prefix = "jerry "

[log]
level = "INFO"
console = true

[plugins]
packages = { jerry = "src.jerry_bot.plugins" }

plugins = ["core:*", "jerry:*"]
[plugins.perms_cli]
use_cog = true # Use permissions CLI cog
